server:
  port: 9090

spring:
  application:
    name: GATEWAY-API
  cloud:
    gateway:
      routes:
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: library-service
                fallbackUri: forward:/libraryServiceFallBack

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/loans/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/userServiceFallBack

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /actuator
      cors:
        allowed-origins: true
  endpoint:
    health:
      enabled: true
      show-details: always

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
